name: grabbit_project
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  geolocator: ^10.1.0
  http: ^0.13.6
  flutter_blue_plus: ^1.31.13
  permission_handler: ^11.3.1
  flutter_local_notifications:
    path: lib_custom/flutter_local_notifications
  timezone: ^0.9.2
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0



#firebase_core:
#cloud_firestore:
#firebase_auth

flutter:
  uses-material-design: true
  assets:
    # 루트에 assets 폴더로 옮겼다면 ↓
    # assets/grabbit_logo.png
    # 만약 lib/assets에 그대로 두고 싶다면 위 줄 지우고 아래 줄 사용
     - lib/assets/grabbit_logo.png
