name: grabbit_project
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  # 공통
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  flutter_blue_plus: ^1.31.13
  timezone: ^0.9.2

  # Firebase
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.0   
  flutter_local_notifications: 17.2.3



flutter:
  uses-material-design: true
  assets:
    - lib/assets/grabbit_logo.png
